version: "3.9"
services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yze3agr@BQV8uct-rzj
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,marcusolsson-csv-datasource
    depends_on:
      - redis
      - postgres
    volumes:
      - ./grafana-volume:/home/grafana

  redis:
    container_name: redis_inst
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    container_name: postgresql_database
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}