version: "3.9"
services:
  redis:
    container_name: redis_inst
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    container_name: postgresql_database
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}